server:
  port: 10220

logging.level.root: INFO
logging.level.com.sofaboot.sofa: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dataintegration?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 10.21.86.35
    port: 6379
    password: dataos
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接

#配置MyBatis
mybatis:
  mapper-locations: classpath*:com/youngdatafan/di/run/management/server/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mvc:
    view:
      prefix: /
      suffix: .html

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 异步线程池配置
dp:
  async:
    taskExecutor:
      corePoolSize: 100
      maxPoolSize: 200
      queueCapacity: 200
      keepAliveSeconds: 60
  savemodel:
    taskExecutor:
      corePoolSize: 10
      maxPoolSize: 200
      queueCapacity: 200
      keepAliveSeconds: 60
  project:
    execute:
      deleteTmpFile: false
      defaultDataSource: ENGINE_CLICKHOUSE
    restExecute:
      deleteTmpFile: false
      defaultDataSource: ENGINE_CLICKHOUSE
    datasource:
      maxWaitTimeout: 10000
      maxFreeTimeMinute: 180
      clearCron: 0 7 */1 * * ?
  preview:
    downloadMaxRow: 600000
kettle:
  datasource:
    engine:
      # mysql源数据库
      metadata:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dataintegration?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        hikari:
          minimum-idle: 1
          maximum-pool-size: 10
          max-lifetime: 1800000
          idle-timeout: 600000
          connection-timeout: 30000
          connection-test-query: SELECT 1
  engine:
    name: Pentaho local
    thread:
      corePoolSize: 10
      maximumPoolSize: 200
      keepAliveTime: 60
    # 系统变量配置
    variable:
      systemVariables:
        - { "name": "batchDay",  "desc": "批量日期(前一天，格式：yyyy-MM-dd)",  "expression": "date_to_string(addDate(sysdate(),5,-1),\"yyyy-MM-dd\")",  "formatSting": "yyyy-MM-dd" }
        - { "name": "batchDateTime",  "desc": "批量日期时间戳(前一天，格式：yyyy-MM-dd HH:mm:ss)",  "expression": "date_to_string(addDate(sysdate(),5,-1),\"yyyy-MM-dd HH:mm:ss\")",  "formatSting": "yyyy-MM-dd HH:mm:ss" }
        - { "name": "currentDay",  "desc": "当前日期(格式：yyyy-MM-dd)",  "expression": "date_to_string(sysdate(),\"yyyy-MM-dd\")",  "formatSting": "yyyy-MM-dd" }
        - { "name": "currentDateTime",  "desc": "当前日期时间戳(格式：yyyy-MM-dd HH:mm:ss)",  "expression": "date_to_string(sysdate(),\"yyyy-MM-dd HH:mm:ss\")",  "formatSting": "yyyy-MM-dd HH:mm:ss" }

  global:
    map:
      sql.engine.db.inputPlugin.schema: tmp
      sql.engine.db.temp.schema: tmp
      sql.engine.db.saveModel.schema: pdi
      sql.engine.db.insert.batchSize: 1000
      sql.engine.db.cache.customizeTmpTable: true


ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长

jasypt:
  encryptor:
    password: fdasjfldjskfkf787fda9r321
